---
title: "Big_Data"
author: "Yufei Zhao"
date: "12/20/2016"
output: html_document
---
```{r}
library(ggplot2)
library('tidyverse')
```


```{r}
data1 <- read.csv("data_1.csv", header = T)
data1$hotel_continent <- factor(data1$hotel_continent)
data1$srch_destination_type_id <- factor(data1$srch_destination_type_id)
```

Data Exploration

#part1

```{r}
ggplot(data = data1) + geom_point(mapping = aes(x = user_location_city,y = orig_destination_distance))+geom_abline(slope = 0, intercept = 3000, col = 2)
```


#part2

```{r}
ggplot(data=data1) + geom_bar(mapping = aes(x = hotel_continent,fill = ..count..), color = 1) + labs(x = 'Hotel Continent', y = 'Count')
```

```{r}
ggplot(data = data1) + geom_histogram(mapping = aes(x = hotel_market, fill = ..count..), color = 2)
```


```{r}
ggplot(data = data1, mapping = aes(x = hotel_market)) + 
  geom_freqpoly(mapping = aes(colour = hotel_continent), binwidth = 50)
```


#part3
```{r}
ggplot(data1, aes(hotel_continent, fill=srch_destination_type_id))+geom_bar()
```


#part4
```{r}
ggplot(data = data1) + geom_bar(mapping = aes(x = hotel_cluster, fill = ..count..) )
```





